# Generated by Django 5.0.4 on 2025-10-31 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('strategy', models.CharField(max_length=100)),
                ('starting_capital', models.FloatField()),
                ('interval', models.CharField(default='1d', max_length=10)),
                ('total_return_pct', models.FloatField()),
                ('cagr_pct', models.FloatField()),
                ('sharpe', models.FloatField()),
                ('max_drawdown_pct', models.FloatField()),
                ('trades', models.IntegerField()),
                ('winrate_pct', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='when the backtester was ran')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ticker', 'strategy', 'start_date', 'end_date'], name='core_backte_ticker_ad0910_idx')],
            },
        ),
        migrations.CreateModel(
            name='EquityPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('equity', models.FloatField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_points', to='core.backtestrun')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['run', 'timestamp'], name='core_equity_run_id_59a9ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('entry_price', models.FloatField()),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('size', models.FloatField()),
                ('pnl', models.FloatField(blank=True, null=True)),
                ('return_pct', models.FloatField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_detail', to='core.backtestrun')),
            ],
            options={
                'ordering': ['entry_time'],
                'indexes': [models.Index(fields=['run', 'entry_time'], name='core_trade_run_id_24a74c_idx')],
            },
        ),
    ]
